#!/usr/bin/env bash
PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/sbin:/usr/sbin
export PATH

exitval=0

if [ "$(git config --local user.name)" = "" ]; then
  echo "[ERROR] user.name is not set locally"
  exitval=1
fi

if [ "$(git config --local user.email)" = "" ]; then
  echo "[ERROR] user.email is not set locally"
  exitval=1
fi

exit ${exitval}
